### ISSUE TITLE
코코아팟 설치

### ISSUE THREAD

**Issue by dp221125** [nalong-enter/servicename-ios#1]
1. Moya
2. FLEX

설치 끝나고 make project하면 한번에 다 되게끔 해주세요

**Comment by kyeongwan** [comment]
이게 Moya

**Comment by dp221125** [comment]
> 이게 Moya

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 프로젝트 셋팅 중에 역할 분배를 하고 있습니다.
